export class userData {
    id:number;
    name:string;
    username:string;
    email:string;
    address:string;
    street:string;
    suite:string;
    city:string;
    zipcode:string;
    geo:object;
    lat:string;
    lng:string;
    phone:string;
    website:string;
    company:object;
    catchPhrase:string;
    bs:string;
}